name: CI

on: [push, pull_request, workflow_dispatch]

env:
  BUNDLE_JOBS: 4

# jobs defined in the order we want them listed in the Actions UI
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        # the job name is composed by these attributes
        ruby:
          - '4.0'
        os:
          - ubuntu-24.04
        gemfile:
          - Gemfile
        include:
          - { os: windows-latest, ruby: ruby, allow-failure: true }
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      BUNDLE_WITHOUT: development:coverage
      # Workaround for Windows JRuby JDK issue
      # https://github.com/ruby/setup-ruby/issues/339
      # https://github.com/jruby/jruby/issues/7182#issuecomment-1112953015
      JAVA_OPTS: -Djdk.io.File.enableADS=true
    steps:
      - uses: actions/checkout@v6

      - name: Install libidn (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install libidn11-dev

      - name: Install libidn (macOS)
        if: startsWith(matrix.os, 'macos')
        run: brew install libidn

      - name: Setup ruby
        continue-on-error: ${{ matrix.allow-failure || false }}
        id: setupruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
          ruby-version: ${{ matrix.ruby }}

      - name: Install gems
        continue-on-error: ${{ matrix.allow-failure || false }}
        id: bundle
        run: bundle install

      - name: Run specs
        continue-on-error: ${{ matrix.allow-failure || false }}
        id: specs
        run: ruby -S bundle exec rake spec
        shell: bash

      # because continue-on-error marks the steps as pass if they fail
      - name: >-
          Setup ruby outcome: ${{ steps.setupruby.outcome }}
        run: echo NOOP
      - name: >-
          Install gems outcome: ${{ steps.bundle.outcome }}
        run: echo NOOP
      - name: >-
          Run specs outcome: ${{ steps.specs.outcome }}
        run: echo NOOP
